version: 2.1

orbs:
  gcp-gcr: ttrahan/gcp-gcr@dev:alpha

jobs:
  test-orb-commands:
    executor: gcp-gcr/default
    steps:
      # test orb commands
      - gcp-gcr/auth:
          google-project-id: citric-biplane-94023
      - gcp-gcr/build-image:
          registry-url: us.gcr.io
          google-project-id: citric-biplane-94023
          image: sample-image
          tag: $CIRCLE_BRANCH.$CIRCLE_BUILD_NUMBER
          path_to_Dockerfile: .
      - gcp-gcr/push-image:
          registry-url: us.gcr.io
          google-project-id: citric-biplane-94023
          image: sample-image
          tag: $CIRCLE_BRANCH.$CIRCLE_BUILD_NUMBER

workflows:
  build_and_push_image:
    jobs:
      - orb-tools/pack-and-validate-orb:
          path: ./src/
          workspace-path: orb-packed/
          artifact-path: orb-packed/

      - orb-tools/publish-dev-orb:
          namespace: circleci
          orb-name: hello-build
          label: ${CIRCLE_BRANCH}
          dev-token-variable: "$CIRCLECI_API_TOKEN"
          workspace-path: orb-packed/
          requires: [orb-tools/pack-and-validate-orb]

      - orb-tools/increment-orb:
          orb-path: orb-packed/orb.yml
          namespace: circleci
          orb-name: hello-build
          segment: "patch"
          workspace-path: orb-packed/
          release-token-variable: "$CIRCLECI_API_TOKEN"
          requires: [orb-tools/pack-and-validate-orb]
          filters:
            branches:
              only: master

      # test orb commands
      - test-orb-commands:
          context: ttrahan

      # test orb jobs
      - gcp-gcr/install_and_initialize_gcr:
          context: ttrahan
          google-project-id: citric-biplane-94023
          google-compute-zone: us-west1-b
      - gcp-gcr/use_google_image_and_initialize_gcr:
          context: ttrahan
          google-project-id: citric-biplane-94023
          google-compute-zone: us-west1-b
